name: chart-bulk-scan pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: bulk-scan
      chartReleaseName: chart-bulk-scan-ci-release
      chartNamespace: chart-tests
      helmDeleteWait: "300"
      helmInstallWait: "300"
      helmInstallTimeout: "600"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: bulk-scan
      chartReleaseName: chart-bulk-scan
      chartNamespace: chart-tests
