global:
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  ccdDataStoreUrl: "http://ccd-data-store"
bulk-scan-processor:
  java:
    secrets:
      STORAGE_ACCOUNT_NAME:
        secretRef: storage-secret-{{ .Release.Name }}
        key: storageAccountName
      STORAGE_KEY:
        secretRef: storage-secret-{{ .Release.Name }}
        key: accessKey
  blobstorage:
    resourceGroup: bulk-scan-aks
    teamName: "Software Engineering"
    location: ukwest
    setup:
      containers:
        - bulkscan
        - bulkscan-rejected
        - sscs
ccd:
  postgresql:
    enabled: false
  rpeServiceAuthProvider:
    enabled: true
  draftStoreService:
    enabled: false
  dmStore:
    enabled: false
  paymentApi:
    enabled: false
  managementWeb:
    enabled: false
  apiGatewayWeb:
    enabled: false
  adminWeb:
    enabled: false
  printService:
    enabled: false
  activityApi:
    enabled: false
  testStubsService:
    enabled: false
bulkscan:
  ccd:
    enabled: true
bsp:
  blobstorage:
    enabled: false
dm-store:
  blobstorage:
    enabled: true
postgresql:
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;