global:
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  devMode: true

rpe-service-auth-provider:
  java:
    MICROSERVICEKEYS_CCD_ADMIN: AAAAAAAAAAAAAAAA
    MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
    MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA

bulk-scan-processor:
  java:
    environment:
      STORAGE_BLOB_SELECTED_CONTAINER: "bulkscan"
      STORAGE_URL: "https://$(STORAGE_ACCOUNT_NAME).blob.core.windows.net"
    secrets:
      STORAGE_ACCOUNT_NAME:
        secretRef: storage-secret-{{ .Release.Name }}
        key: storageAccountName
      STORAGE_KEY:
        secretRef: storage-secret-{{ .Release.Name }}
        key: accessKey
  blobstorage:
    resourceGroup: bulk-scan-aks
    teamName: "Software Engineering"
    location: ukwest
    setup:
      containers:
        - bulkscan
        - bulkscan-rejected
        - sscs
        - dm-store
        - definition-store
bulk-scan-payment-processor:
  java:
    secrets:
      IDAM_CLIENT_SECRET:
        disabled: true
      SITE_ID_PROBATE:
        disabled: true
      SITE_ID_DIVORCE:
        disabled: true
      SITE_ID_FINREM:
        disabled: true
    environment:
      IDAM_CLIENT_SECRET: XXXXXXXXXX
      SITE_ID_PROBATE: "XXX2312"
      SITE_ID_DIVORCE: "XXX2121"
      SITE_ID_FINREM: "XXX3132"
bulk-scan-orchestrator:
  java:
    secrets:
      IDAM_CLIENT_SECRET:
        disabled: true
      IDAM_USERS_BULKSCAN_USERNAME:
        disabled: true
      IDAM_USERS_BULKSCAN_PASSWORD:
        disabled: true
      IDAM_USERS_CMC_USERNAME:
        disabled: true
      IDAM_USERS_CMC_PASSWORD:
        disabled: true
      IDAM_USERS_DIV_USERNAME:
        disabled: true
      IDAM_USERS_DIV_PASSWORD:
        disabled: true
      IDAM_USERS_PROBATE_USERNAME:
        disabled: true
      IDAM_USERS_PROBATE_PASSWORD:
        disabled: true
      IDAM_USERS_SSCS_USERNAME:
        disabled: true
      IDAM_USERS_SSCS_PASSWORD:
        disabled: true

ccd:
  postgresql:
    enabled: false
  s2s:
    enabled: false
  draftStore:
    enabled: false
  dmStore:
    enabled: false
  paymentApi:
    enabled: false
  managementWeb:
    enabled: false
  apiGatewayWeb:
    enabled: false
  adminWeb:
    enabled: false
  printService:
    enabled: false
  activityApi:
    enabled: false
  testStubsService:
    enabled: false
  definitionImporter:
    enabled: false
  userProfileImporter:
    enabled: false
  blobstorage:
    enabled: false
  emAnnotation:
    enabled: false
  ccpay:
    enabled: false
  ccd-definition-store-api:
    java:
      secrets:
        STORAGE_ACCOUNT_NAME:
          secretRef: storage-secret-{{ .Release.Name }}
          key: storageAccountName
        STORAGE_ACCOUNT_KEY:
          secretRef: storage-secret-{{ .Release.Name }}
          key: accessKey
ccpay:
  payment-api:
    java:
      environment:
        GOV_PAY_AUTH_KEY_CMC: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3
        GOV_PAY_AUTH_KEY_DIVORCE_FRONTEND: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3
        GOV_PAY_AUTH_KEY_PROBATE_FRONTEND: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3


bulkscan:
  ccd:
    enabled: true
  s2s:
    enabled: true
bsp:
  blobstorage:
    enabled: true
dm-store:
  blobstorage:
    enabled: false
postgresql:
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;