global:
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  devMode: true


bulk-scan-processor:
  java:
    environment:
      STORAGE_BLOB_SELECTED_CONTAINER: "bulkscan"
      STORAGE_URL: "https://$(STORAGE_ACCOUNT_NAME).blob.core.windows.net"
    secrets:
      STORAGE_ACCOUNT_NAME:
        secretRef: storage-secret-{{ .Release.Name }}
        key: storageAccountName
      STORAGE_KEY:
        secretRef: storage-secret-{{ .Release.Name }}
        key: accessKey
  blobstorage:
    resourceGroup: bulk-scan-aks
    teamName: "Software Engineering"
    location: ukwest
    setup:
      containers:
        - bulkscan
        - bulkscan-rejected
        - sscs
        - dm-store
ccd:
  postgresql:
    enabled: false
  s2s:
    enabled: false
  draftStore:
    enabled: false
  dmStore:
    enabled: false
  paymentApi:
    enabled: false
  managementWeb:
    enabled: false
  apiGatewayWeb:
    enabled: false
  adminWeb:
    enabled: false
  printService:
    enabled: false
  activityApi:
    enabled: false
  testStubsService:
    enabled: false
  definitionImporter:
    enabled: false
  userProfileImporter:
    enabled: false
  blobstorage:
    enabled: false
  emAnnotation:
    enabled: false
  ccpay:
    enabled: false
bulkscan:
  ccd:
    enabled: true
bsp:
  blobstorage:
    enabled: true
dm-store:
  blobstorage:
    enabled: false
postgresql:
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;